### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by ghost** [Hkattelu/Messenger-Bulk-Archiver#1]
I can't get any of the three buttons to work. I'm available for further information, but I'm not sure what would be useful.

**Comment by Hkattelu** [comment]
Hi,

Have you tried refreshing the page and re-running? If so - do you get any console errors in dev tools? (Assuming you are using Chrome, and your messenger language is English)

**Comment by ghost** [comment]
body{font-family:Helvetica,Arial;font-size:13px}OK, when I switch to English, it works. Perhaps it would be beneficial to mention it somewhere.   dnia 2 czerwca 2019 o 18:59:57, Himanshu Kattelu (notifications@github.com) napisał: 





Hi,
Have you tried refreshing the page and re-running? If so - do
you get any console errors in dev tools? (Assuming you are using
Chrome, and your messenger language is English)
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by Hkattelu** [comment]
I'll add the feature to work for other languages later today. Originally I had released the chrome extension for this with the language English (United States) but I realize now that it's not clear it works only in English.

**Comment by Hkattelu** [comment]
I've made a change that *should* get this extension working in every language. I've made the change in the newest version in [this commit](https://github.com/Hkattelu/Messenger-Bulk-Archiver/commit/d5e2afe980716d87525679552f5716e87ab20adc) and have updated the chrome extension in the web store to include this change.

Marking this as closed.
