### ISSUE TITLE
Chrome Extension Not Found

### ISSUE THREAD

**Issue by ciordia9** [Hkattelu/Messenger-Bulk-Archiver#2]
Link in Readme (https://chrome.google.com/webstore/detail/messenger-bulk-archiver/iohchpnpecckgjpopcbndbdgcgkbkjmn?hl=en&gl=US) leads to a 404.

Looking directly in Google Chrome Store I cannot find it under any search terms.

**Comment by Hkattelu** [comment]
Hi, the chrome extension got taken down due to a request from Facebook :(. Unfortunately, there isn't much I can do about this. If you want to use this extension still, you can clone or download the repo and then open it in chrome in developer mode.

**Comment by Hkattelu** [comment]
Updated README to remove the chrome extension link, marking this as closed.
